config/routes.rb
Inference::Application.routes.draw do
  resources :dashboards

  root :to => "widgets#index"
  resources :widgets, :only => [:index, :edit, :update, :new, :create, :destroy]
  resources :dashboard_lattices, :only => [:create, :destroy]
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  attr_protected nil

  has_many :dashboard_lattices
  has_many :widgets, :through => :dashboard_lattices
end

app/models/dashboard_lattice.rb
class DashboardLattice < ActiveRecord::Base
  belongs_to :dashboard
  belongs_to :widget
  attr_protected nil
end

app/models/widget.rb
class Widget < ActiveRecord::Base
  attr_protected nil

  def image_path
    "#{Rails.root}/public/widgets/#{id}/chart.jpg"
  end

  def image_execute(minutes_ago = minutes_ago)
    begin
      Inference::Script.new(self, minutes_ago).execute
    rescue Exception => e
      puts "XXX: error parsing: #{e.message}"
      puts "XXX: stact:"
      puts e.backtrace.join("\n")
      return e.message
    end

    image_url
  end

  def image_url
    "/widgets/#{id}/chart.jpg"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  http_basic_authenticate_with :name => "inference", :password => "pass"

  after_filter :metrics

  private

  def metrics
    Inference::Client.insert("key.request", Time.now, rand(100))
  end
end

app/controllers/dashboard_lattices_controller.rb
class DashboardLatticesController < ApplicationController
  def create
    @dashboard_lattice = DashboardLattice.new(params[:dashboard_lattice])
    if @dashboard_lattice.save
      redirect_to @dashboard_lattice.dashboard, :notice => "Successfully created dashboard_lattice."
    else
      redirect_to @dashboard_lattice.dashboard, :alert => "Some error trying to create dashboard_lattice."
    end
  end

  def destroy
    @dashboard_lattice = DashboardLattice.find(params[:id])
    @dashboard_lattice.destroy
    redirect_to @dashboard_lattice.dashboard, :notice => "Successfully destroyed dashboard_lattice."
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @dashboards = Dashboard.all
  end

  def new
    @dashboard = Dashboard.new
  end

  def create
    @dashboard = Dashboard.new(params[:dashboard])
    if @dashboard.save
      redirect_to @dashboard, :notice => "Successfully created dashboard."
    else
      render :action => 'new'
    end
  end

  def show
    @dashboard = Dashboard.find(params[:id])
  end

  def update
    @dashboard = Dashboard.find(params[:id])
    if @dashboard.update_attributes(params[:dashboard])
      redirect_to @dashboard, :notice  => "Successfully updated dashboard."
    else
      render :action => 'edit'
    end
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  def index
    @widgets = Widget.all
  end

  def new
    @widget = Widget.new
  end

  def create
    @widget = Widget.new(params[:widget])
    if @widget.save
      redirect_to edit_widget_path(@widget), :notice => "Successfully created widget."
    else
      render :action => 'new'
    end
  end

  def edit
    @widget = Widget.find(params[:id])
  end

  def update
    @widget = Widget.find(params[:id])
    if @widget.update_attributes(params[:widget])
      redirect_to edit_widget_path(@widget), :notice  => "Successfully updated widget."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @widget = Widget.find(params[:id])
    @widget.destroy
    redirect_to widgets_url, :notice => "Successfully destroyed widget."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_class(actual_menu_name)
    menus = {
      :widgets => ["/", "/widgets.*"],
      :dashboards => ["/dashboards.*"],
    }

    menus.each do |menu_name, menu_paths|
      return "active" if actual_menu_name == menu_name && menu_paths.any? { |e| request.fullpath.gsub(/\?.*/, "") =~ /^#{e}$/ }
    end

    return "no-active"
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/dashboards/index.html.erb
<% title "Dashboards" %>

<p><%= link_to "New Dashboard", new_dashboard_path, :class => "btn" %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th class="span8">Name</th>
      <th>Num Widgets</th>
    </tr>
  </thead>
  <tbody>
    <% for dashboard in @dashboards %>
      <tr>
        <td><%= link_to dashboard.name, dashboard %></td>
        <td><%= dashboard.widgets.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboards/new.html.erb
<% title "New Dashboard" %>

<%= form_for @dashboard, :html => { :class => "form" } do |f| %>
  <%= f.error_messages %>
  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name, :class => "span6" %>
    </div>
  </div>
  <p><%= f.submit :class => "btn btn-primary" %></p>
<% end %>


<p><%= link_to "Back to List", dashboards_path %></p>

app/views/dashboards/show.html.erb
<% title "Dashboards / #{@dashboard.name}" %>

<p>
  <%= link_to "View All", dashboards_path %>
</p>

<%= form_for @dashboard, :html => { :class => "form-inline" } do |f| %>
  <fieldset>
    <legend>Edit Dashboard</legend>
    <%= f.label :name %>
    <%= f.text_field :name %>
    &nbsp;&nbsp;
    <%= f.label :minutes_ago %>
    <%= f.text_field :minutes_ago %>
    <%= f.submit "Update", :class => "btn btn-primary" %>
  </fieldset>
<% end %>

<%= form_for DashboardLattice.new(:dashboard => @dashboard), :html => { :class => "form-inline" } do |f| %>
  <fieldset>
    <legend>Add Widget</legend>
    <%= f.hidden_field :dashboard_id %>
    <%= f.select( :widget_id, Widget.all.map { |e| [ e.name, e.id ] } ) %>
    <%= f.submit "Add Widget", :class => "btn btn-primary" %>
  </fieldset>
<% end %>

<ul class="thumbnails row">
  <% @dashboard.dashboard_lattices.each do |dashboard_lattice| %>
    <%= puts "XXX: dashboard_lattice: #{dashboard_lattice.inspect}" %>
    <li class="span4">
      <div class="thumbnail">
        <% if !dashboard_lattice.widget.script.blank? %>
          <%= image_tag dashboard_lattice.widget.image_execute(@dashboard.minutes_ago) %>
        <% end %>
        <div class="caption">
          <h3><%= dashboard_lattice.widget.name %></h3>
          <p><%= dashboard_lattice.widget.text %></p>
          <p>
            <%= link_to "Edit", edit_widget_path(dashboard_lattice.widget), :class => "btn" %>
            <%= link_to "Remove", dashboard_lattice, :class => "btn btn-danger", :method => :delete %>
          </p>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= javascript_include_tag "/assets/jquery/jquery.js" %>
    <%= javascript_include_tag "/assets/rails/jquery_ujs.js" %>

    <%= csrf_meta_tag %>

    <%= stylesheet_link_tag "/assets/bootstrap/css/bootstrap.css" %>
    <%= stylesheet_link_tag "/assets/bootstrap/css/bootstrap-responsive.css" %>
    <%= javascript_include_tag "/assets/bootstrap/js/bootstrap.js" %>

    <%= yield(:head) %>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Inference", root_path, :class => "brand" %></a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="<%= menu_class(:widgets) %>"><%= link_to "Widgets", widgets_path %></li>
              <li class="<%= menu_class(:dashboards) %>"><%= link_to "Dashboards", dashboards_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div> <!-- container -->
  </body>
</html>

app/views/widgets/_form.html.erb
<%= form_for @widget, :html => { :class => "form" } do |f| %>

  <div class="row-fluid">
    <div class="span6">
      <%= f.error_messages %>

      <fieldset>
        <legend>Widget Info</legend>
        <div class="control-group">
          <%= f.label :name, :class => "control-label" %>
          <div class="controls">
            <%= f.text_field :name, :class => "span12" %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :script, :class => "control-label" %>
          <div class="controls">
            <%= f.text_area :script, :class => "span12", :rows => 5 %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :text, :class => "control-label" %>
          <div class="controls">
            <%= f.text_area :text, :class => "span12", :rows => 5 %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :minutes_ago, :class => "control-label" %>
          <div class="controls">
            <%= f.text_field :minutes_ago %>
          </div>
        </div>
      </fieldset>

      <%= f.submit :class => "btn btn-primary" %>
    </div>

    <% if !@widget.script.blank? %>
      <div class="span6">
        <fieldset>
          <legend>Graph</legend>
          <%= image_tag @widget.image_execute %>
        </fieldset>
      </div>
    <% end %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<% title "Edit Widget" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @widget %> |
  <%= link_to "View All", widgets_path %>
</p>

app/views/widgets/index.html.erb
<% title "Widgets" %>

<p><%= link_to "New Widget", new_widget_path, :class => "btn" %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th class="span8">Name</th>
      <th>Last Update</th>
    </tr>
  </thead>
  <tbody>
    <% for widget in @widgets %>
      <tr>
        <td><%= link_to widget.name, edit_widget_path(widget) %></td>
        <td><%= widget.updated_at.to_s(:localdb) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/widgets/new.html.erb
<% title "New Widget" %>

<%= render 'form' %>

<p><%= link_to "Back to List", widgets_path %></p>

app/views/widgets/show.html.erb
<% title "Widget" %>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>
<p>
  <strong>Script:</strong>
  <%= @widget.script %>
</p>

<% if !@widget.script.blank? %>
  <p>
    <strong>Image:</strong>
    <%= image_tag @widget.image_url %>
  </p>
<% end %>

<p>
  <%= link_to "Edit", edit_widget_path(@widget) %> |
  <%= link_to "Destroy", @widget, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", widgets_path %>
</p>